###
@organizationId = optimaGrowth
POST http://localhost:8080/v1/organization/{{organizationId}}/license
Accept: application/json
Content-Type: application/json
Accept-Language: es

{
  "licenseId": "0235431845",
  "organizationId": "optima Growth",
  "description": "Software product",
  "productName": "Ostock",
  "licenseType": "complete"
}