server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
      routes:
        - id: organization-service # This optional ID is an arbitrary route ID
          uri: lb://organization-service # Sets the route's destination URI
          predicates: # The path, although set by the load() method, is just another option
          - Path=/organization/**
          filters:
          - RewritePath=/organization/(?<path>.*), /$\{path}
        - id: licensing-service
          uri: lb://licensing-service
          predicates:
          - Path=/license/**
          filters:
          - RewritePath=/license/(?<path>.*), /$\{path}

management:
  endpoints:
    web:
      exposure:
        include: "*"