version: '3'

services:
  licensingservice:
    image: rocklee1108/licensing-service:0.0.1-SNAPSHOT

    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenservice"

networks:
  backend:
    driver: bridge