name: Commit Stage
on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        project: [
          cloud_native_spring_in_action/catalog-service,
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
            - name: Code vulnerability scanning
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: ${{ matrix.project }} # Path to the project directory
          fail-build: false # Whether to fail the build in the event of security vulnerabilities
          severity-cutoff: high
          acs-report-enable: true
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }} # Fetches the report from the output of the previous step
      - name: Build, unit tests and integration tests
        run: |
          cd ${{ matrix.project }}
          chmod +x gradlew
          ./gradlew build