name: Commit Stage
on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        project: [
          cloud_native_spring_in_action/catalog-service,
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd ${{ matrix.project }}
          chmod +x gradlew
          ./gradlew build